# Generated by Django 5.1.7 on 2025-04-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_sent_messages',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество отправленных сообщений'),
        ),
    ]
