# Generated by Django 5.1.7 on 2025-04-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_count_sent_messages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_view_all_users", "Can view all users"), ("can_block_users", "Can block users")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
