# Generated by Django 5.1.7 on 2025-03-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_alter_mailing_recipients_alter_mailing_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempts",
            name="mail_server_response",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ почтового сервиса"),
        ),
    ]
