# Generated by Django 5.1.7 on 2025-04-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_mailing_owner_mailingrecipient_owner_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['status'], 'permissions': [('can_view_all_mailings', 'Can view all mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingrecipient',
            options={'ordering': ['email'], 'permissions': [('can_view_all_mailing_recipients', 'Can view all mailing recipients')], 'verbose_name': 'Получатель рассылки', 'verbose_name_plural': 'Получатели рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['subject'], 'permissions': [('can_view_all_messages', 'Can view all mailing messages')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
